In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/round1_josaa_22.csv")
df.head()

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,Round
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,9193,11771,1
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),16138,20164,1
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1605,1744,1
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),3159,3159,1
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Gender-Neutral,3997,4297,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10022 entries, 0 to 10021
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Institute              10022 non-null  object
 1   Academic Program Name  10022 non-null  object
 2   Quota                  10022 non-null  object
 3   Seat Type              10022 non-null  object
 4   Gender                 10022 non-null  object
 5   Opening Rank           10022 non-null  object
 6   Closing Rank           10022 non-null  object
 7   Round                  10022 non-null  int64
dtypes: int64(1), object(7)
memory usage: 626.5+ KB

In [ ]:
df.nunique()

Institute                 114
Academic Program Name     189
Quota                       6
Seat Type                  10
Gender                      2
Opening Rank             7040
Closing Rank             7402
Round                       1
dtype: int64

In [ ]:
df.columns = [col.replace(" ","_") for col in df.columns]

In [ ]:
df.columns

Index(['Institute', 'Academic_Program_Name', 'Quota', 'Seat_Type', 'Gender',
       'Opening_Rank', 'Closing_Rank', 'Round'],
      dtype='object')

In [ ]:
df[df['Opening_Rank'].str.contains('P', regex="True")]

,Institute,Academic_Program_Name,Quota,Seat_Type,Gender,Opening_Rank,Closing_Rank,Round
73,Indian Institute of Technology Bhubaneswar,Electronics and Communication Engineering (4 Y...,AI,EWS (PwD),Gender-Neutral,11P,11P,1
82,Indian Institute of Technology Bhubaneswar,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OPEN (PwD),Gender-Neutral,68P,68P,1
139,Indian Institute of Technology Bombay,"Aerospace Engineering (4 Years, Bachelor of Te...",AI,OBC-NCL (PwD),Gender-Neutral,14P,14P,1
142,Indian Institute of Technology Bombay,"Aerospace Engineering (4 Years, Bachelor of Te...",AI,SC (PwD),Gender-Neutral,8P,8P,1
160,Indian Institute of Technology Bombay,"Chemical Engineering (4 Years, Bachelor of Tec...",AI,OBC-NCL (PwD),Gender-Neutral,10P,13P,1
...,...,...,...,...,...,...,...,...
2679,Indian Institute of Technology Tirupati,"Electrical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL (PwD),Gender-Neutral,71P,71P,1
2716,Indian Institute of Technology Jammu,"Computer Science and Engineering (4 Years, Bac...",AI,OPEN (PwD),Gender-Neutral,18P,18P,1
2744,Indian Institute of Technology Jammu,"Materials Engineering (4 Years, Bachelor of Te...",AI,ST,Female-only (including Supernumerary),258P,258P,1
2778,Indian Institute of Technology Dharwad,"Computer Science and Engineering (4 Years, Bac...",AI,OBC-NCL (PwD),Gender-Neutral,35P,35P,1
2810,Indian Institute of Technology Dharwad,"Interdisciplinary Sciences (5 Years, Bachelor ...",AI,ST,Female-only (including Supernumerary),256P,256P,1

In [ ]:
#Assuming that P does not hold any significant meaning
df['Opening_Rank']=df['Opening_Rank'].replace("P","", regex=True)
df['Closing_Rank']=df['Closing_Rank'].replace("P","", regex=True)

In [ ]:
df[df['Opening_Rank'].str.contains('P')]

Empty DataFrame
Columns: [Institute, Academic_Program_Name, Quota, Seat_Type, Gender, Opening_Rank, Closing_Rank, Round]
Index: []

In [ ]:
data_types_dict = {'Opening_Rank': int, 'Closing_Rank': int}
df = df.astype(data_types_dict)
df.dtypes

Institute                object
Academic_Program_Name    object
Quota                    object
Seat_Type                object
Gender                   object
Opening_Rank              int64
Closing_Rank              int64
Round                     int64
dtype: object

In [ ]:
seat_types=df['Seat_Type'].unique()
seat_types

array(['OPEN', 'EWS', 'OBC-NCL', 'SC', 'ST', 'OPEN (PwD)', 'EWS (PwD)',
       'OBC-NCL (PwD)', 'SC (PwD)', 'ST (PwD)'], dtype=object)

In [ ]:
df['Gender'].unique()

array(['Gender-Neutral', 'Female-only (including Supernumerary)'],
      dtype=object)

In [ ]:
rank=int(input("Enter your rank: "))
print("Seat_Types:",seat_types)
seat=input("Enter your seat type (copy from the above list): ")
gender=(input("Enter your gender [1 for gender-neutral and 2 for female-only (including supernumerary)]:"))
if gender=='1':
  gender='Gender-Neutral'
elif gender == '2':
  gender='Female-only (including Supernumerary)'
df_output=df.query('Opening_Rank <= @rank and Closing_Rank >= @rank and Seat_Type == @seat and Gender == @gender')
df_output[["Institute","Academic_Program_Name"]]

Enter your rank: 9999
Seat_Types: ['OPEN' 'EWS' 'OBC-NCL' 'SC' 'ST' 'OPEN (PwD)' 'EWS (PwD)' 'OBC-NCL (PwD)'
 'SC (PwD)' 'ST (PwD)']
Enter your seat type (copy from the above list): EWS
Enter your gender [1 for gender-neutral and 2 for female-only (including supernumerary)]:1

,Institute,Academic_Program_Name
3739,National Institute of Technology Agartala,"Computer Science and Engineering (4 Years, Bac..."
3973,National Institute of Technology Calicut,"Computer Science and Engineering (4 Years, Bac..."
4026,National Institute of Technology Calicut,Electronics and Communication Engineering (4 Y...
4086,National Institute of Technology Calicut,"Mechanical Engineering (4 Years, Bachelor of T..."
4471,National Institute of Technology Goa,"Computer Science and Engineering (4 Years, Bac..."
4651,National Institute of Technology Hamirpur,"Electrical Engineering (4 Years, Bachelor of T..."
4673,National Institute of Technology Hamirpur,Electronics and Communication Engineering (4 Y...
5604,National Institute of Technology Raipur,"Electrical Engineering (4 Years, Bachelor of T..."
5673,National Institute of Technology Raipur,"Mechanical Engineering (4 Years, Bachelor of T..."
7226,"National Institute of Technology, Tiruchirappalli",Instrumentation and Control Engineering (4 Yea...
7248,"National Institute of Technology, Tiruchirappalli","Mechanical Engineering (4 Years, Bachelor of T..."
7755,Sardar Vallabhbhai National Institute of Techn...,"Mathematics (5 Years, Integrated Master of Sci..."
7789,Sardar Vallabhbhai National Institute of Techn...,"Physics (5 Years, Integrated Master of Science)"
9262,"Birla Institute of Technology, Mesra, Ranchi","Chemical Engineering (4 Years, Bachelor of Tec..."
9382,"Indian Institute of Carpet Technology, Bhadohi","Carpet and Textile Technology (4 Years, Bachel..."
9407,"Institute of Technology, Guru Ghasidas Vishwav...","Chemical Engineering (4 Years, Bachelor of Tec..."
9533,Sant Longowal Institute of Engineering and Tec...,"Food Technology (4 Years, Bachelor of Technology)"
9687,"Punjab Engineering College, Chandigarh","Computer Science and Engineering (4 Years, Bac..."
9697,"Punjab Engineering College, Chandigarh",Computer Science Engineering (Data Science) (4...
9889,Ghani Khan Choudhary Institute of Engineering ...,"Food Technology (4 Years, Bachelor of Technology)"
9923,National Institute of Food Technology Entrepre...,"Food Technology and Management (4 Years, Bache..."
9973,"Institute of Chemical Technology, Mumbai: Indi...","Chemical Engineering (5 Years, Integrated Mast..."